# Generated by Django 4.0 on 2021-12-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('rate', models.IntegerField(default=0, verbose_name='Оценка')),
                ('engage_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='КДПВ')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, verbose_name='Ник')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.author', verbose_name='Автор'),
        ),
    ]
